import time
import json
from seleniumwire import webdriver


driver = webdriver.Chrome()

driver.get('https://hyperskill.org/login?next=/study-plan&utm_source=homepage')
time.sleep(15)

driver.find_element('xpath', "//input[@type='email']").send_keys('ya@ya.ru')
driver.find_element('xpath', "//input[@type='password']").send_keys('Alexey')
driver.find_element('xpath', "//button[@type='submit']").submit()

time.sleep(15)

payload = {'email': 'ya@ya.ru', "password": 'Alexey'}

for request in driver.requests:
    if request.method == "POST" and "/api/profiles/login" in request.url:
        assert payload == json.loads(request.body.decode()), "POST request body does not contain expected data"

driver.quit()

# Пример 2: подменить ответ на 401 Unauthorized
#
# def interceptor(request):
#     if "secure" in request.url:
#         request.create_response(
#             status_code=401,
#             headers={'Content-Type': 'application/json'},
#             body='{"error": "Unauthorized"}'
#         )
# Применение: можно протестировать, показывает ли UI “Вы не авторизованы”, если сервер вернёт 401.

# Пример 3: подменить изображение
#
# import time
# import json
# from seleniumwire import webdriver
#
# def my_interceptor(request):
#     if "freeconferencecall-logo.svg" in request.url:
#         with open("/Users/manikosto/PycharmProjects/SeleniumLastWave/files/image.png", "rb") as f:
#             img_bytes = f.read()
#         request.create_response(
#             status_code=200,
#             headers={"Content-Type": "image/jpeg"},
#             body=img_bytes
#         )
#
#
# driver = webdriver.Chrome()
# driver.request_interceptor = my_interceptor
#
# driver.get('https://www.freeconferencecall.com/global/pl/login')
# input()
#
# driver.quit()
# Применение: можно протестировать, показывает ли UI подменную картинку, например лого и как сайт реагирует при невалидных изображениях.

# Пример: подменить HTML-страницу
#
# request.create_response(
#     status_code=200,
#     headers={'Content-Type': 'text/html'},
#     body="""
#     <html>
#         <h1>Mocked Page</h1>
#         <p>This page was generated by Selenium Wire</p>
#     </html>
#     """
# )
